package net.azisaba.vanilife.registry

import net.azisaba.vanilife.item.*

object CustomItemTypes: KeyedRegistry<CustomItemType>() {
    val APPLE_JAM = register(AppleJam)
    val BACON = register(Bacon)
    val BANANA = register(Banana)
    val BELL_PEPPER = register(BellPepper)
    val BUTTER = register(Butter)
    val BUTTERED_POTATO = register(ButteredPotato)
    val CAVENIUM = register(Cavenium)
    val CHEESE = register(Cheese)
    val CHERRY = register(Cherry)
    val CUCUMBER = register(Cucumber)
    val DOUGH = register(Dough)
    val EGGPLANT = register(Eggplant)
    val FRUIT_SANDWICH = register(FruitSandwich)
    val GRAPE = register(Grape)
    val JAPANESE_RADISH = register(JapaneseRadish)
    val KNIFE = register(Knife)
    val LETTUCE = register(Lettuce)
    val MAGNITE = register(Magnite)
    val MAYONNAISE = register(Mayonnaise)
    val MONEY_1000 = register(Money.MONEY_1000)
    val MONEY_5000 = register(Money.MONEY_5000)
    val MONEY_10000 = register(Money.MONEY_10000)
    val NAPPA_CABBAGE = register(NappaCabbage)
    val ONION = register(Onion)
    val PEACH = register(Peach)
    val ROCK_SALT = register(RockSalt)
    val SALT = register(Salt)
    val SANDWICH = register(Sandwich)
    val SLICED_TOMATO = register(SlicedTomato)
    val STRAWBERRY = register(Strawberry)
    val TOMATO = register(Tomato)
    val WHEAT_FLOUR = register(WheatFlour)
    val WHITE_BREAD = register(WhiteBread)
    val YEAST = register(Yeast)
}