name: vanilife
version: '0.0.0'
main: net.azisaba.vanilife.Vanilife
bootstrapper: net.azisaba.vanilife.VanilifeBootstrap
api-version: '1.21'
dependencies:
  server:
    kunectron:
      load: AFTER
permissions:
  vanilife.*:
    description: This permission includes all Vanilife permissions.
    default: op
    children:
      vanilife.items: true
  vanilife.items:
    description: This permission gives access to the items gui.
    default: op